### ISSUE TITLE
 SilentPatchGF Causing game error at launch!

### ISSUE THREAD

**Issue by NATO2000** [CookiePLMonster/SilentPatchGF#8]
Hello！I am a American now living in Taiwan

My OS is Windows XP SP3 with GTX280

This game installed from an  ISO image ,

game version unknow,but its language is "Traditional Chinese characters"

I am very happy that this site offers a lot of solutions

(https://pcgamingwiki.com/wiki/The_Godfather:_The_Game),

it offers that widescreen solutions and frame unlocking, via "SilentPatchGF" from https://github.com/CookiePLMonster/SilentPatchGF/releases

unfortunately, on my computer,this SilentPatchGF Directly causing the game to fail to launch (SilentPatchGF.zip had gave user
 an special dinput8.dll")

System prompt "Cannot locate program input point SHGetKnownFolderPath on dynamic link library shell32.dll"

So I try using "regsvr32 E:\gf\dinput8.dll" to solve the dll error,but I failed ,dll Register cannot complete

please，help me 

I also  try windows 7 x64, there is no dll error but, there is a new error "ASI loader:unable to load silentpathgf.asi,error 998"

**Comment by CookiePLMonster** [comment]
Hey,

SPGF doesn't and will not support Windows XP for several reasons:
- The main and biggest fix it provides is not needed on XP
- Other fixes (related to registry Virtual Store) are also nearly inexistant on XP
- Universal ASI Loader (dinput8.dll) which SPGF ships in order to load into the game does not support XP
- It's been nearly 5 years since this system officially died

If you're really stuck on XP, I recommend just not using SPGF. Even if it worked, it wouldn't bring you noticeable benefits.

**Comment by NATO2000** [comment]
Hey, it is an honor to have your attention!

I also try windows 7 x64, there is no dll error but, there is a new error

"ASI loader:Unable to load SilentPathGF.asi,Error 998"

Can you help me?

I am waiting for you Online

**Comment by GenesisFR** [comment]
Offtopic but I'd like to mention you need to be running an admin command prompt to register DLLs (with regsvr32).

**Comment by CookiePLMonster** [comment]
Closing because it concerns an unsupported OS.
